services:
  database:
    image: postgres:17
    container_name: lush_postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    ports:
      - '5432:5432'
